name: 'Repo Settings Manager'
description: 'Github Action to setup repository settings'
author: 'seblaporte'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  REPOSITORIES:
    description: 'Github repositories to setup. Default will get all public repositories for your username'
    required: false
    default: 'ALL'
  ALLOW_ISSUES:
    description: 'Whether or not to allow issues on the repo'
    required: false
    default: 'true'
  ALLOW_PROJECTS:
    description: 'Whether or not to allow projects on the repo'
    required: false
    default: 'true'
  ALLOW_WIKI:
    description: 'Whether or not to allow wiki on the repo'
    required: false
    default: 'true'
  SQUASH_MERGE:
    description: 'Whether or not to allow squash merges on the repo'
    required: false
    default: 'true'
  MERGE_COMMIT:
    description: 'Whether or not to allow merge commits on the repo'
    required: false
    default: 'true'
  REBASE_MERGE:
    description: 'Whether or not to allow rebase merges on the repo'
    required: false
    default: 'true'
  DELETE_HEAD:
    description: 'Whether or not to delete head branch after merges'
    required: false
    default: 'false'
  SQUASH_PR_TITLE:
    description: 'Whether or not to use the PR title as default commit name when using squash-merge'
    required: false
    default: 'false'
  BRANCHES_PROTECTION_NAME:
    description: 'Branches name pattern for branches protection rule'
    required: false
    default: 'master'
  BRANCH_PROTECTION_REQUIRED_REVIEWERS:
    description: 'Number of required reviewers for branch protection rule'
    required: false
    default: '1'
  BRANCH_PROTECTION_DISMISS:
    description: 'Dismiss stale pull request approvals when new commits are pushed'
    required: false
    default: 'true'
  BRANCH_PROTECTION_CODE_OWNERS:
    description: 'Require review from Code Owners'
    required: false
    default: 'true'
  BRANCH_PROTECTION_ENFORCE_ADMINS:
    description: 'Enforce branch protection rules for repo admins'
    required: false
    default: 'false'
  TOKEN:
    description: 'Personal access token with Repo privileges'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'